patchedDependencies:
  astro-tweet@0.0.6: patches/astro-tweet.patch
  expressive-code-twoslash@0.6.1: patches/expressive-code-twoslash@0.6.1.patch

allowBuilds:
  esbuild: false
  msgpackr-extract: false
  msw: false
  sharp: false
